fastlane_version "1.30.2"

lane :carthage_update do
  carthage
end

lane :test do
  sh "xcodebuild test -project ../SoundCloudSwift.xcodeproj -scheme 'SoundCloudSwift iOS' -sdk iphonesimulator9.0 ONLY_ACTIVE_ARCH=NO | xcpretty -c"
  sh "xcodebuild test -project ../SoundCloudSwift.xcodeproj -scheme 'SoundCloudSwift OSX' ONLY_ACTIVE_ARCH=NO | xcpretty -c"
end
